epoll_server: test_epoll_server.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

length_prefixed_socket: test_length_prefixed_socket.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

socket_connect: test_socket_connect.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

packet_parser: test_packet_parser.cpp
	g++ $^ -o test.out -std=c++11
	./test.out

serializer: test_serializer.cpp
	g++ $^ -o test.out -std=c++11
	./test.out

function_traits: test_function_traits.cpp
	g++ $^ -o test.out -std=c++11
	./test.out
