threaded_stub: test_threaded_stub.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

thread_pool: test_thread_pool.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

netpacket_object: test_netpacket_object.cpp
	g++ $^ -o test.out -std=c++11
	./test.out

simple_stub: test_simple_stub.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

epoll_client: test_epoll_client.cpp
	g++ $^ -o client.out -std=c++11 -lpthread
	./client.out

epoll_server: test_epoll_server.cpp
	g++ $^ -o server.out -std=c++11 -lpthread
	./server.out

length_prefixed_socket: test_length_prefixed_socket.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

socket_connect: test_socket_connect.cpp
	g++ $^ -o test.out -std=c++11 -lpthread
	./test.out

packet_parser: test_packet_parser.cpp
	g++ $^ -o test.out -std=c++11
	./test.out

serializer: test_serializer.cpp
	g++ $^ -o test.out -std=c++11
	./test.out

function_traits: test_function_traits.cpp
	g++ $^ -o test.out -std=c++11
	./test.out
